### ISSUE TITLE
Spaceship

### ISSUE THREAD

**Issue by CDVoidwalker** [Uniwersum-narusza/Uniwersum-Narusza-#4]
Zaimplementować statek gracza o w klasie Spaceship.cs z Texture2D i Vector2 na pozycje który wykorzystuje IUpdateable i IDrawable, ma sprawdzać w Update() przyciśnięcie klawiszy space, lewej strzałki i prawej, wypuszczać pocisk zaimplementowany w Bullet.cs po wciśnięciu spacji który również wykorzystuje IUpdateable i IDrawable  jak również dodawać i odejmować od swojej pozycji na X po wciskaniu lewej/prawej strzałki

**Comment by CancerV3** [comment]
Model gotowy :3
